# Generated by Django 3.2.3 on 2021-05-19 07:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 16, 44, 12, 487489)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_movie',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
