# Generated by Django 3.2.3 on 2021-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_acheivement'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheivement',
            name='content',
            field=models.TextField(default='acheivement content'),
            preserve_default=False,
        ),
    ]
