
# Generated by Django 3.2.3 on 2021-05-21 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('overview', models.TextField(null=True)),
                ('poster_path', models.TextField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('vote_average', models.IntegerField(null=True)),
                ('popularity', models.IntegerField(null=True)),
                ('movie_dislike_users', models.ManyToManyField(related_name='dislike_movies', to=settings.AUTH_USER_MODEL)),
                ('movie_like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
                ('movie_wish_users', models.ManyToManyField(related_name='wish_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('favorite_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_genres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
