# Generated by Django 3.2.3 on 2021-05-19 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20210519_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_dislike_users',
            field=models.ManyToManyField(related_name='dislike_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_like_users',
            field=models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='wish_users',
            field=models.ManyToManyField(related_name='wish_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('favorite_users', models.ManyToManyField(related_name='favorite_genres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
