# Generated by Django 3.2.3 on 2021-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210523_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('poster_path', models.TextField(null=True)),
            ],
        ),
    ]
