# Generated by Django 3.2.3 on 2021-05-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20210520_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='favorite_users',
        ),
        migrations.AddField(
            model_name='genre',
            name='favorite_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_dislike_users',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_dislike_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_movies', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_like_users',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_like_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_movies', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='wish_users',
        ),
        migrations.AddField(
            model_name='movie',
            name='wish_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wish_movies', to='accounts.user'),
            preserve_default=False,
        ),
    ]
