# Generated by Django 3.2.3 on 2021-05-20 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_auto_20210520_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='favorite_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_genres', to='accounts.user'),
            preserve_default=False,
        ),
    ]
